# -*- coding: utf-8 -*-
"""Homework 2nd.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wx5DRjVwCSNrid5kO4gR5GZmVCagvrrI

### 1.請設計一個程式計算圓周長與圓面積，依輸入的半徑計算圓周長與圓面積。輸岀結果為浮點數
"""

import math

PI=math.pi

radius= float(input())

print("Radius=%.2f"%radius)
print("Perimeter=%.2f"%(2*radius*PI))
print("Area=%.2f"%(pow(radius,2)*PI))

"""### 2.創建一個簡單的腳本，用於收集和處理用戶的個人資料，包括姓名、年齡、身高 （米）、和喜愛的顏色。然後，根據這些資料。
輸出一個格式化的個人資料摘要。
•輸入：讓用戶分別輸入他們的姓名（字符串）、年齡 （整數）、身高 （浮點數，單位為米）、和喜愛的顏色（字符串）
•處理：收集這些資料，並將它們存儲在適當的資料結構中 （考慮使用字典）。
•輸出：根據收集到的資料，輸出一個格式化的字符串，摘要用戶的個人資料，例如：“John Doe, 30歲，身高1.75米，喜愛的顧
色是藍色。"
"""

def collect_user_data():
    # 收集用戶輸入的資料
    name = input("請輸入您的姓名：")
    age = int(input("請輸入您的年齡："))
    height = float(input("請輸入您的身高（米）："))
    favorite_color = input("請輸入您喜愛的顏色：")

    # 將資料存儲在字典中
    user_data = {
        "姓名": name,
        "年齡": age,
        "身高": height,
        "喜愛的顏色": favorite_color
    }

    return user_data

def format_user_summary(user_data):
    # 格式化個人資料摘要
    summary = f"{user_data['姓名']}, {user_data['年齡']}歲，身高{user_data['身高']}米，喜愛的顏色是{user_data['喜愛的顏色']}。"
    return summary

if __name__ == "__main__":
    user_info = collect_user_data()
    user_summary = format_user_summary(user_info)
    print(user_summary)

"""### 3.請使用選擇叙述撰寫一程式，讓使用者輸入一個整數，然後判斷它是否為偶數 (even)"""

a=int(input())

if a%2 ==0:
  print("%d is an even number."%a)
else:
  print("%d is not an even number."%a)